/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as ReservationIndexImport } from './routes/reservation/index'
import { Route as TreatmentsIdImport } from './routes/treatments/$id'
import { Route as ReservationNewImport } from './routes/reservation/new'
import { Route as ReservationIdImport } from './routes/reservation/$id'
import { Route as CustomersIdImport } from './routes/customers/$id'
import { Route as AuthedPostsImport } from './routes/_authed/posts'
import { Route as AuthedPostsIndexImport } from './routes/_authed/posts.index'
import { Route as AuthedRecordNewImport } from './routes/_authed/record/new'
import { Route as AuthedPostsPostIdImport } from './routes/_authed/posts.$postId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ReservationIndexRoute = ReservationIndexImport.update({
  id: '/reservation/',
  path: '/reservation/',
  getParentRoute: () => rootRoute,
} as any)

const TreatmentsIdRoute = TreatmentsIdImport.update({
  id: '/treatments/$id',
  path: '/treatments/$id',
  getParentRoute: () => rootRoute,
} as any)

const ReservationNewRoute = ReservationNewImport.update({
  id: '/reservation/new',
  path: '/reservation/new',
  getParentRoute: () => rootRoute,
} as any)

const ReservationIdRoute = ReservationIdImport.update({
  id: '/reservation/$id',
  path: '/reservation/$id',
  getParentRoute: () => rootRoute,
} as any)

const CustomersIdRoute = CustomersIdImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthedPostsRoute = AuthedPostsImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPostsIndexRoute = AuthedPostsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRoute,
} as any)

const AuthedRecordNewRoute = AuthedRecordNewImport.update({
  id: '/record/new',
  path: '/record/new',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPostsPostIdRoute = AuthedPostsPostIdImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsImport
      parentRoute: typeof AuthedImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdImport
      parentRoute: typeof rootRoute
    }
    '/reservation/$id': {
      id: '/reservation/$id'
      path: '/reservation/$id'
      fullPath: '/reservation/$id'
      preLoaderRoute: typeof ReservationIdImport
      parentRoute: typeof rootRoute
    }
    '/reservation/new': {
      id: '/reservation/new'
      path: '/reservation/new'
      fullPath: '/reservation/new'
      preLoaderRoute: typeof ReservationNewImport
      parentRoute: typeof rootRoute
    }
    '/treatments/$id': {
      id: '/treatments/$id'
      path: '/treatments/$id'
      fullPath: '/treatments/$id'
      preLoaderRoute: typeof TreatmentsIdImport
      parentRoute: typeof rootRoute
    }
    '/reservation/': {
      id: '/reservation/'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdImport
      parentRoute: typeof AuthedPostsImport
    }
    '/_authed/record/new': {
      id: '/_authed/record/new'
      path: '/record/new'
      fullPath: '/record/new'
      preLoaderRoute: typeof AuthedRecordNewImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexImport
      parentRoute: typeof AuthedPostsImport
    }
  }
}

// Create and export the route tree

interface AuthedPostsRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteChildren: AuthedPostsRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteWithChildren = AuthedPostsRoute._addFileChildren(
  AuthedPostsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedPostsRoute: typeof AuthedPostsRouteWithChildren
  AuthedRecordNewRoute: typeof AuthedRecordNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRoute: AuthedPostsRouteWithChildren,
  AuthedRecordNewRoute: AuthedRecordNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/posts': typeof AuthedPostsRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reservation/new': typeof ReservationNewRoute
  '/treatments/$id': typeof TreatmentsIdRoute
  '/reservation': typeof ReservationIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/record/new': typeof AuthedRecordNewRoute
  '/posts/': typeof AuthedPostsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/customers/$id': typeof CustomersIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reservation/new': typeof ReservationNewRoute
  '/treatments/$id': typeof TreatmentsIdRoute
  '/reservation': typeof ReservationIndexRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/record/new': typeof AuthedRecordNewRoute
  '/posts': typeof AuthedPostsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/posts': typeof AuthedPostsRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/reservation/new': typeof ReservationNewRoute
  '/treatments/$id': typeof TreatmentsIdRoute
  '/reservation/': typeof ReservationIndexRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/record/new': typeof AuthedRecordNewRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/posts'
    | '/customers/$id'
    | '/reservation/$id'
    | '/reservation/new'
    | '/treatments/$id'
    | '/reservation'
    | '/posts/$postId'
    | '/record/new'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/customers/$id'
    | '/reservation/$id'
    | '/reservation/new'
    | '/treatments/$id'
    | '/reservation'
    | '/posts/$postId'
    | '/record/new'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/posts'
    | '/customers/$id'
    | '/reservation/$id'
    | '/reservation/new'
    | '/treatments/$id'
    | '/reservation/'
    | '/_authed/posts/$postId'
    | '/_authed/record/new'
    | '/_authed/posts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  CustomersIdRoute: typeof CustomersIdRoute
  ReservationIdRoute: typeof ReservationIdRoute
  ReservationNewRoute: typeof ReservationNewRoute
  TreatmentsIdRoute: typeof TreatmentsIdRoute
  ReservationIndexRoute: typeof ReservationIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  CustomersIdRoute: CustomersIdRoute,
  ReservationIdRoute: ReservationIdRoute,
  ReservationNewRoute: ReservationNewRoute,
  TreatmentsIdRoute: TreatmentsIdRoute,
  ReservationIndexRoute: ReservationIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login",
        "/logout",
        "/signup",
        "/customers/$id",
        "/reservation/$id",
        "/reservation/new",
        "/treatments/$id",
        "/reservation/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/posts",
        "/_authed/record/new"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_authed/posts": {
      "filePath": "_authed/posts.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/posts/$postId",
        "/_authed/posts/"
      ]
    },
    "/customers/$id": {
      "filePath": "customers/$id.tsx"
    },
    "/reservation/$id": {
      "filePath": "reservation/$id.tsx"
    },
    "/reservation/new": {
      "filePath": "reservation/new.tsx"
    },
    "/treatments/$id": {
      "filePath": "treatments/$id.tsx"
    },
    "/reservation/": {
      "filePath": "reservation/index.tsx"
    },
    "/_authed/posts/$postId": {
      "filePath": "_authed/posts.$postId.tsx",
      "parent": "/_authed/posts"
    },
    "/_authed/record/new": {
      "filePath": "_authed/record/new.tsx",
      "parent": "/_authed"
    },
    "/_authed/posts/": {
      "filePath": "_authed/posts.index.tsx",
      "parent": "/_authed/posts"
    }
  }
}
ROUTE_MANIFEST_END */
